// Generated by: supabase gen types typescript --local
// DO NOT EDIT MANUALLY — regenerate with: npm run db:types
// This file represents the EXACT database schema at the time of generation.

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json }
  | Json[];

export interface Database {
  public: {
    Tables: {
      app_settings: {
        Row: {
          key: string;
          value: string;
          updated_at: string;
        };
        Insert: {
          key: string;
          value: string;
          updated_at?: string;
        };
        Update: {
          key?: string;
          value?: string;
          updated_at?: string;
        };
      };
      profiles: {
        Row: {
          id: string;
          email: string | null;
          phone: string | null;
          full_name: string;
          role: 'visiteur' | 'locataire' | 'bailleur' | 'admin';
          avatar_url: string | null;
          country: string | null;
          is_premium: boolean;
          consent_apdp: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id: string;
          email?: string | null;
          phone?: string | null;
          full_name?: string;
          role?: 'visiteur' | 'locataire' | 'bailleur' | 'admin';
          avatar_url?: string | null;
          country?: string | null;
          is_premium?: boolean;
          consent_apdp?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          email?: string | null;
          phone?: string | null;
          full_name?: string;
          role?: 'visiteur' | 'locataire' | 'bailleur' | 'admin';
          avatar_url?: string | null;
          country?: string | null;
          is_premium?: boolean;
          consent_apdp?: boolean;
          created_at?: string;
          updated_at?: string;
        };
      };
      residences: {
        Row: {
          id: string;
          owner_id: string;
          title: string;
          description: string | null;
          type: 'studio' | 'chambre' | 'appartement' | 'villa' | 'magasin' | 'terrain';
          price_monthly: number;
          deposit: number;
          bedrooms: number;
          bathrooms: number;
          surface: number | null;
          address: string | null;
          city: string | null;
          zone: string | null;
          lat: number | null;
          lng: number | null;
          geom: unknown | null;
          photos: string[];
          status: 'libre' | 'occupee' | 'en_visite' | 'maintenance';
          is_published: boolean;
          is_verified: boolean;
          views_count: number;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          owner_id: string;
          title: string;
          description?: string | null;
          type?: 'studio' | 'chambre' | 'appartement' | 'villa' | 'magasin' | 'terrain';
          price_monthly: number;
          deposit?: number;
          bedrooms?: number;
          bathrooms?: number;
          surface?: number | null;
          address?: string | null;
          city?: string | null;
          zone?: string | null;
          lat?: number | null;
          lng?: number | null;
          geom?: unknown | null;
          photos?: string[];
          status?: 'libre' | 'occupee' | 'en_visite' | 'maintenance';
          is_published?: boolean;
          is_verified?: boolean;
          views_count?: number;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          owner_id?: string;
          title?: string;
          description?: string | null;
          type?: 'studio' | 'chambre' | 'appartement' | 'villa' | 'magasin' | 'terrain';
          price_monthly?: number;
          deposit?: number;
          bedrooms?: number;
          bathrooms?: number;
          surface?: number | null;
          address?: string | null;
          city?: string | null;
          zone?: string | null;
          lat?: number | null;
          lng?: number | null;
          geom?: unknown | null;
          photos?: string[];
          status?: 'libre' | 'occupee' | 'en_visite' | 'maintenance';
          is_published?: boolean;
          is_verified?: boolean;
          views_count?: number;
          created_at?: string;
          updated_at?: string;
        };
      };
      conversations: {
        Row: {
          id: string;
          residence_id: string;
          landlord_id: string;
          tenant_id: string;
          last_message_at: string | null;
          last_message_preview: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          residence_id: string;
          landlord_id: string;
          tenant_id: string;
          last_message_at?: string | null;
          last_message_preview?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          residence_id?: string;
          landlord_id?: string;
          tenant_id?: string;
          last_message_at?: string | null;
          last_message_preview?: string | null;
          created_at?: string;
        };
      };
      messages: {
        Row: {
          id: string;
          conversation_id: string;
          sender_id: string;
          body: string | null;
          attachments: string[];
          kind: 'text' | 'image' | 'document' | 'visit_request' | 'visit_agreed' | 'system';
          read_at: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          conversation_id: string;
          sender_id: string;
          body?: string | null;
          attachments?: string[];
          kind?: 'text' | 'image' | 'document' | 'visit_request' | 'visit_agreed' | 'system';
          read_at?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          conversation_id?: string;
          sender_id?: string;
          body?: string | null;
          attachments?: string[];
          kind?: 'text' | 'image' | 'document' | 'visit_request' | 'visit_agreed' | 'system';
          read_at?: string | null;
          created_at?: string;
        };
      };
      leases: {
        Row: {
          id: string;
          residence_id: string;
          tenant_id: string;
          landlord_id: string;
          monthly_rent: number;
          deposit: number;
          start_date: string;
          end_date: string | null;
          status: 'active' | 'terminated' | 'pending';
          date_fn_couverture: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          residence_id: string;
          tenant_id: string;
          landlord_id: string;
          monthly_rent: number;
          deposit: number;
          start_date: string;
          end_date?: string | null;
          status?: 'active' | 'terminated' | 'pending';
          date_fn_couverture: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          residence_id?: string;
          tenant_id?: string;
          landlord_id?: string;
          monthly_rent?: number;
          deposit?: number;
          start_date?: string;
          end_date?: string | null;
          status?: 'active' | 'terminated' | 'pending';
          date_fn_couverture?: string;
          created_at?: string;
          updated_at?: string;
        };
      };
      payments: {
        Row: {
          id: string;
          lease_id: string;
          tenant_id: string;
          landlord_id: string;
          amount: number;
          period_start: string;
          period_end: string;
          method: 'mobile_money' | 'cash';
          provider: 'mtn' | 'moov' | 'celtiis' | 'cash';
          provider_ref: string | null;
          checkout_url: string | null;
          status: 'pending' | 'confirmed' | 'rejected';
          confirmed_by: string | null;
          confirmed_at: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          lease_id: string;
          tenant_id: string;
          landlord_id: string;
          amount: number;
          period_start: string;
          period_end: string;
          method: 'mobile_money' | 'cash';
          provider?: 'mtn' | 'moov' | 'celtiis' | 'cash';
          provider_ref?: string | null;
          checkout_url?: string | null;
          status?: 'pending' | 'confirmed' | 'rejected';
          confirmed_by?: string | null;
          confirmed_at?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          lease_id?: string;
          tenant_id?: string;
          landlord_id?: string;
          amount?: number;
          period_start?: string;
          period_end?: string;
          method?: 'mobile_money' | 'cash';
          provider?: 'mtn' | 'moov' | 'celtiis' | 'cash';
          provider_ref?: string | null;
          checkout_url?: string | null;
          status?: 'pending' | 'confirmed' | 'rejected';
          confirmed_by?: string | null;
          confirmed_at?: string | null;
          created_at?: string;
        };
      };
      receipts: {
        Row: {
          id: string;
          payment_id: string;
          lease_id: string;
          tenant_id: string;
          landlord_id: string;
          amount: number;
          period_start: string;
          period_end: string;
          file_url: string | null;
          signature_hash: string | null;
          signed_by: string | null;
          signed_at: string | null;
          status: 'pending_signature' | 'signed';
          created_at: string;
        };
        Insert: {
          id?: string;
          payment_id: string;
          lease_id: string;
          tenant_id: string;
          landlord_id: string;
          amount: number;
          period_start: string;
          period_end: string;
          file_url?: string | null;
          signature_hash?: string | null;
          signed_by?: string | null;
          signed_at?: string | null;
          status?: 'pending_signature' | 'signed';
          created_at?: string;
        };
        Update: {
          id?: string;
          payment_id?: string;
          lease_id?: string;
          tenant_id?: string;
          landlord_id?: string;
          amount?: number;
          period_start?: string;
          period_end?: string;
          file_url?: string | null;
          signature_hash?: string | null;
          signed_by?: string | null;
          signed_at?: string | null;
          status?: 'pending_signature' | 'signed';
          created_at?: string;
        };
      };
      notifications: {
        Row: {
          id: string;
          user_id: string;
          type: 'message' | 'payment' | 'receipt' | 'lease' | 'overdue' | 'system' | 'visit';
          title: string;
          body: string | null;
          data: Json | null;
          read_at: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          type?: 'message' | 'payment' | 'receipt' | 'lease' | 'overdue' | 'system' | 'visit';
          title: string;
          body?: string | null;
          data?: Json | null;
          read_at?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          type?: 'message' | 'payment' | 'receipt' | 'lease' | 'overdue' | 'system' | 'visit';
          title?: string;
          body?: string | null;
          data?: Json | null;
          read_at?: string | null;
          created_at?: string;
        };
      };
    };
    Views: {
      [_ in never]: never;
    };
    Functions: {
      admin_list_residences: {
        Args: { limit?: number };
        Returns: Database['public']['Tables']['residences']['Row'][];
      };
      admin_list_users: {
        Args: { limit?: number };
        Returns: Database['public']['Tables']['profiles']['Row'][];
      };
      admin_moderate_residence: {
        Args: { p_residence_id: string; p_action: 'approve' | 'reject'; p_reason?: string };
        Returns: void;
      };
      admin_set_landlord_verified: {
        Args: { p_user_id: string; p_verified: boolean };
        Returns: void;
      };
      admin_set_premium: {
        Args: { p_user_id: string; p_is_premium: boolean };
        Returns: void;
      };
      admin_verify_residence: {
        Args: { p_residence_id: string };
        Returns: void;
      };
      admin_unpublish_residence: {
        Args: { p_residence_id: string };
        Returns: void;
      };
      complete_landlord_onboarding: {
        Args: {
          p_business_name: string;
          p_tax_id: string | null;
          p_momo_provider: 'mtn' | 'moov' | 'celtiis' | null;
          p_momo_number: string | null;
          p_bank_name: string | null;
          p_bank_iban: string | null;
        };
        Returns: void;
      };
      list_my_favorite_ids: {
        Args: Record<PropertyKey, never>;
        Returns: string[];
      };
      list_my_favorites: {
        Args: Record<PropertyKey, never>;
        Returns: Database['public']['Tables']['residences']['Row'][];
      };
      list_reviews: {
        Args: { p_residence_id: string };
        Returns: {
          id: string;
          residence_id: string;
          tenant_id: string;
          tenant_name?: string;
          rating: number;
          comment: string | null;
          created_at: string;
        }[];
      };
      mark_all_notifications_read: {
        Args: Record<PropertyKey, never>;
        Returns: void;
      };
      mark_conversation_read: {
        Args: { p_conversation_id: string };
        Returns: void;
      };
      toggle_favorite: {
        Args: { p_residence_id: string };
        Returns: boolean;
      };
      get_my_billing: {
        Args: Record<PropertyKey, never>;
        Returns: Record<string, unknown> | null;
      };
      admin_stats: {
        Args: Record<PropertyKey, never>;
        Returns: {
          users: { total: number; by_role: Record<string, number> };
          residences: { total: number; by_status: Record<string, number> };
          leases: { total: number };
          payments: { confirmed_count: number; total_collected_xof: number };
        };
      };
      agree_visit: {
        Args: { p_conversation_id: string; p_agreed: boolean; p_note?: string };
        Returns: void;
      };
      create_lease: {
        Args: {
          p_residence_id: string;
          p_tenant_id: string;
          p_start_date: string;
          p_monthly_rent: number;
          p_deposit?: number;
          p_end_date?: string | null;
        };
        Returns: string;
      };
      delete_my_account: {
        Args: Record<PropertyKey, never>;
        Returns: void;
      };
      get_conversation: {
        Args: { p_conversation_id: string };
        Returns: {
          id: string;
          residence_id: string;
          landlord_id: string;
          tenant_id: string;
          last_message_at: string | null;
          last_message_preview: string | null;
          residence: {
            id: string;
            title: string;
            photos: string[];
            price_monthly: number;
            city: string;
            zone: string | null;
          } | null;
          peer: {
            id: string;
            full_name: string;
            role: string;
            avatar_url: string | null;
          } | null;
          unread_count: number;
        } | null;
      };
      get_residence: {
        Args: { p_residence_id: string };
        Returns: Database['public']['Tables']['residences']['Row'] & {
          owner: {
            id: string;
            full_name: string;
            phone: string | null;
            avatar_url: string | null;
            is_premium: boolean;
            is_verified_landlord: boolean;
          } | null;
          distance_km?: number | null;
          rating_avg?: number | null;
          rating_count?: number | null;
        } | null;
      };
      increment_residence_views: {
        Args: { p_id: string };
        Returns: void;
      };
      is_admin: {
        Args: Record<PropertyKey, never>;
        Returns: boolean;
      };
      list_messages: {
        Args: { p_conversation_id: string };
        Returns: Database['public']['Tables']['messages']['Row'][];
      };
      list_my_conversations: {
        Args: Record<PropertyKey, never>;
        Returns: Database['public']['Tables']['conversations']['Row'] & {
          residence: {
            id: string;
            title: string;
            photos: string[];
            price_monthly: number;
            city: string;
            zone: string | null;
          } | null;
          peer: {
            id: string;
            full_name: string;
            role: string;
            avatar_url: string | null;
          } | null;
          unread_count: number;
        }[];
      };
      list_my_leases: {
        Args: Record<PropertyKey, never>;
        Returns: (Database['public']['Tables']['leases']['Row'] & {
          residence: Database['public']['Tables']['residences']['Row'] | null;
          tenant: Database['public']['Tables']['profiles']['Row'] | null;
          landlord: Database['public']['Tables']['profiles']['Row'] | null;
        })[];
      };
      list_my_payments: {
        Args: Record<PropertyKey, never>;
        Returns: (Database['public']['Tables']['payments']['Row'] & {
          lease: Database['public']['Tables']['leases']['Row'] | null;
        })[];
      };
      list_my_receipts: {
        Args: Record<PropertyKey, never>;
        Returns: (Database['public']['Tables']['receipts']['Row'] & {
          landlord: Database['public']['Tables']['profiles']['Row'] | null;
        })[];
      };
      list_my_residences: {
        Args: Record<PropertyKey, never>;
        Returns: (Database['public']['Tables']['residences']['Row'] & {
          owner: Database['public']['Tables']['profiles']['Row'] | null;
        })[];
      };
      open_conversation: {
        Args: { p_residence_id: string };
        Returns: string;
      };
      report_cash_payment: {
        Args: {
          lease_id: string;
          amount: number;
          period_start: string;
          period_end: string;
        };
        Returns: void;
      };
      search_residences: {
        Args: {
          q?: string | null;
          city?: string | null;
          zone?: string | null;
          min_price?: number | null;
          max_price?: number | null;
          lat?: number | null;
          lng?: number | null;
          radius_km?: number | null;
          type?: string[] | null;
        };
        Returns: Database['public']['Tables']['residences']['Row'] & {
          distance_km?: number | null;
          owner?: {
            id: string;
            full_name: string;
            phone: string | null;
            avatar_url: string | null;
            is_premium: boolean;
            is_verified_landlord: boolean;
          } | null;
        }[];
      };
      set_my_role: {
        Args: { p_role: 'locataire' | 'bailleur' };
        Returns: void;
      };
    };
    Enums: {
      user_role: 'visiteur' | 'locataire' | 'bailleur' | 'admin';
      residence_status: 'libre' | 'occupee' | 'en_visite' | 'maintenance';
      residence_type: 'studio' | 'chambre' | 'appartement' | 'villa' | 'magasin' | 'terrain';
      lease_status: 'active' | 'terminated' | 'pending';
      payment_method: 'mobile_money' | 'cash';
      payment_provider: 'mtn' | 'moov' | 'celtiis' | 'cash';
      payment_status: 'pending' | 'confirmed' | 'rejected';
      notification_type: 'message' | 'payment' | 'receipt' | 'lease' | 'overdue' | 'system' | 'visit';
    };
    CompositeTypes: {
      [_ in never]: never;
    };
  };
}